### ISSUE TITLE
Request for new optional mode :)

### ISSUE THREAD

**Issue by KatHellm** [Oghma-Infinium/Ascensio#1]
Have you considered making an optional toggle mode for kinemortophobics (fear of zombies)? Similar to the one you have of insects :) I know I for one would really find great use in that. (if not, totally understandable, I lack the skill to do it myself for a modlist).

**Comment by bingusthecatto** [comment]
Hello!

I haven't really given a Kinemortophobia patch much thought since paid CC Content, such as the CC zombies, has been removed for the next update of Ascensio (which is unreleased). If you consider Draugr as zombies however, that's a different story and one that I can't help you with unfortunately as patching out all the Draugr would be impossible.

**Comment by KatHellm** [comment]
Hi again!
I didn't know you would be patching out the CC zombies anyways, but I definetely approve! 😃 

I understand patching draugr out completely is pretty impossible, so I'm on the lookout for something that either retextures them to _not_ be zombie-esque, or replaces them with bandits, cultists, vampires or that sort of thing 😄.

Thank you for taking the time to respond to this, I appreciate it!

**Comment by bingusthecatto** [comment]
No problem, I don't know of any mods currently that retexture Draugr to not be zombie-esque, but I'll keep on the lookout! Feel free to stop by the discord and drop a link if you do find any mods that accomplish that so I can add them in :)
